---
- name: Get stats of a file
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: repofile

- name: Add kubernetes Repo
  yum_repository:
    name: kubernetes
    description: YUM Repo Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: 1
    gpgcheck: 1
    enabled: 1

- name: Add Docker Repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: repofile.stat.exists == false
