- name: Get stats of a file
  stat:
    path: /home/vagrant/.kube/config
  register: config

- name: Create kube directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: '0740'
    owner: vagrant
    group: vagrant

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - scp -o StrictHostKeyChecking=no -i /home/vagrant/files/id_rsa root@172.25.10.20:/etc/kubernetes/admin.conf.* /home/vagrant/.kube/config
  when: config.stat.exists == false

- name: Kubeconfig permission
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: '0700'
